//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MishnatYosef.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.ProductInBooking = new HashSet<ProductInBooking>();
        }
    
        public int Code { get; set; }
        public int CodeSale { get; set; }
        public int CodeClient { get; set; }
        public double FinalAmount { get; set; }
        public string PaymentNumber { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sale Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInBooking> ProductInBooking { get; set; }
    }
}
