//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MishnatYosef.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInBooking
    {
        public int Code { get; set; }
        public int CodeBooking { get; set; }
        public int CodeProductInSale { get; set; }
        public int Amount { get; set; }
        public bool C_Betaken_ { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Product Product { get; set; }
    }
}
