//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MishnatYosef.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductInBooking = new HashSet<ProductInBooking>();
            this.ProductInSale = new HashSet<ProductInSale>();
        }
    
        public int Code { get; set; }
        public string NameProduct { get; set; }
        public int CodeTrand { get; set; }
        public int CodeCategory { get; set; }
        public string Picture { get; set; }
        public double Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProductTrand ProductTrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInBooking> ProductInBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInSale> ProductInSale { get; set; }
    }
}
